from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
import os, uuid
from datetime import datetime
from utils.emission_calculator import calculate_cbam_liability

REPORT_DIR = os.getenv("REPORT_DIR", "./reports")
os.makedirs(REPORT_DIR, exist_ok=True)

GREEN = colors.HexColor("#0F5C41")
LIGHT_GREEN = colors.HexColor("#F0FDF8")
GRAY = colors.HexColor("#6B7280")

class ReportService:
    def generate_cbam_report(self, emission_records: list) -> dict:
        report_id = str(uuid.uuid4())[:8].upper()
        filename = f"EcoAudit_CBAM_{report_id}_{datetime.now().strftime('%Y%m%d')}.pdf"
        filepath = os.path.join(REPORT_DIR, filename)
        liability = calculate_cbam_liability(emission_records)
        styles = getSampleStyleSheet()
        doc = SimpleDocTemplate(filepath, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)
        story = [
            Paragraph("EcoAudit", ParagraphStyle("t", parent=styles["Title"], textColor=GREEN, fontSize=22)),
            Paragraph("CBAM Compliance Report", styles["Normal"]),
            HRFlowable(width="100%", thickness=2, color=GREEN, spaceAfter=8),
            Paragraph(f"Report ID: {report_id} | {datetime.now().strftime('%d %B %Y')}", styles["Normal"]),
            Spacer(1, 0.5*cm),
        ]
        summary = [
            ["Metric", "Value"],
            ["Total Emissions", f"{liability['total_emission_kg']:,.2f} kg CO2e"],
            ["Emissions in Tons", f"{liability['total_emission_tons']:,.4f} t CO2e"],
            ["CBAM Cost", f"EUR {liability['total_cbam_cost_eur']:,.2f}"],
        ]
        t = Table(summary, colWidths=["55%", "45%"])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), GREEN),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [LIGHT_GREEN, colors.white]),
            ("FONTSIZE", (0,0), (-1,-1), 10),
            ("TOPPADDING", (0,0), (-1,-1), 8),
            ("BOTTOMPADDING", (0,0), (-1,-1), 8),
            ("LEFTPADDING", (0,0), (-1,-1), 12),
            ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#D1FAE5")),
        ]))
        story += [t, Spacer(1, 1*cm),
            HRFlowable(width="100%", thickness=0.5, color=GRAY),
            Paragraph("Generated by EcoAudit — Carbon Footprint Analysis Platform",
                ParagraphStyle("n", parent=styles["Normal"], fontSize=9, textColor=GRAY))]
        doc.build(story)
        return {
            "report_id": report_id, "file_path": filepath, "filename": filename,
            "total_emissions_kg": liability["total_emission_kg"],
            "total_cbam_cost_eur": liability["total_cbam_cost_eur"],
            "suppliers_included": len(set(r["supplier"] for r in liability["breakdown"])),
            "generated_at": datetime.now().isoformat(),
        }

report_service = ReportService()